### ISSUE TITLE
[1pt] Choose assets - group task

### ISSUE THREAD

**Issue by ichala** [ichala/Javascript-Capstone#19]
Choose images, text, icons, fonts.

**Comment by kwambiee** [comment]
For **Icons**, we will use `<i class="fa fa-heart-o" aria-hidden="true"></i>` from font-awesome. Link to attach is `<script
      src="https://kit.fontawesome.com/a11f8b435e.js"
      crossorigin="anonymous"
    ></script>`
For **fonts** we will use `Roboto`. We will use `@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap');`

**Comment by ichala** [comment]
- we used [Font Awesome](https://fontawesome.com/) for icons
- we applied [Roboto](https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap) as font
- main colors are `#6c757d` & `#F2D2BD`
