### ISSUE TITLE
Capstone Project  Kanban board Setup

### ISSUE THREAD

**Issue by ichala** [ichala/Javascript-Capstone#21]
- Javascript Capstone Project Link : https://github.com/ichala/Javascript-Capstone/projects/1
in this capstone project we are only two people ,  I'm gonna work both me @ichala and @kwambiee together on this project
Student A will be @ichala 
Student B will be @kwambiee

**Comment by Deepakdanger** [comment]
**Hi @Team**, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
